### ISSUE TITLE
W3NS无法正常申请

### ISSUE THREAD

**Issue by punkcanyang** [IntensiveCoLearning/Web3-URL#124]
![image](https://github.com/user-attachments/assets/ca746cf8-5621-4fd6-8f34-461c0127f79c)

尝试好几个名字都无法进入申请的阶段

**Comment by qzhodl** [comment]
可以尝试使用ENS的sepolia的版本来注册域名和使用到web3://，具体详见文档：https://docs.web3url.io/tutorials-on-ethstorage-early-testnet/bind-domain-names-to-your-flatdirectory

**Comment by punkcanyang** [comment]
已经解决，换浏览器，并关掉proxy就好了
