### ISSUE TITLE
关于请假的格式规范确认

### ISSUE THREAD

**Issue by ztm0929** [IntensiveCoLearning/Web3-URL#143]
有两天实际没有学习（也没有commit），但是我发现似乎不知什么原因被自动化脚本标记完成了✅
也许是因为在对应的日期内依然填写了内容？我可以自行修正README吗？  

---

<img width="531" alt="Screenshot 2024-07-23 at 00 48 08" src="https://github.com/user-attachments/assets/2744123d-c552-47db-8e6b-2678f2e7a691">  

---

<img width="231" alt="Screenshot 2024-07-23 at 00 48 43" src="https://github.com/user-attachments/assets/4ede74e5-cc32-42a0-862a-1a09188213d5">

**Comment by DerickIT** [comment]
时间日期内的内容超过10个字符就认为提交了学习笔记，即打卡成功了，
您可以将19，20两天的文本内容删除，没有检测到内容提交就会标记O
