### ISSUE TITLE
可以为仓库开启讨论区吗？（Discussions）

### ISSUE THREAD

**Issue by ztm0929** [IntensiveCoLearning/Web3-URL#42]
便于资料的汇集分享、疑问的探讨交流。

官网论坛的话一方面是关联性不强，另一方面是我自己懒🐶有问题的话也会随时在TG群组里发出，但是我很容易受其他消息干扰分心。（hhh也许我毛病太多了🤣

**Comment by luffythink** [comment]
是要开的，没有及时打开，哈哈。🤣
