### ISSUE TITLE
建议将大家的笔记统一放在文件夹里

### ISSUE THREAD

**Issue by ztm0929** [IntensiveCoLearning/Web3-URL#73]
报名人数较多的情况下，整个文件目录会显得过长，可否迁移到某个新目录下，如 /notes/kevin_WICL1st.md

纯属个人强迫症🌚不过考虑到已经使用了自动化脚本，可能这次迁移会很麻烦，以后的共学仓库可以考虑要不要这样。

**Comment by brucexu-eth** [comment]
这次确实，可能报名人数比较多，整个列表有点长，当时放在一个 notes 可能不利于大家看到其他人的笔记？这里面可能有一些权衡的地方。

**Comment by linghuccc** [comment]
> 报名人数较多的情况下，整个文件目录会显得过长，可否迁移到某个新目录下，如 /notes/kevin_WICL1st.md
> 
> 纯属个人强迫症🌚不过考虑到已经使用了自动化脚本，可能这次迁移会很麻烦，以后的共学仓库可以考虑要不要这样。

这个帖子不应该发表在 Issue 里面，应该发在 Discussion 里面。

**Comment by ztm0929** [comment]
> > 报名人数较多的情况下，整个文件目录会显得过长，可否迁移到某个新目录下，如 /notes/kevin_WICL1st.md
> > 纯属个人强迫症🌚不过考虑到已经使用了自动化脚本，可能这次迁移会很麻烦，以后的共学仓库可以考虑要不要这样。
> 
> 这个帖子不应该发表在 Issue 里面，应该发在 Discussion 里面。

哈哈我没怎么用过GitHub，我分不清楚Issues和Discussions的区别😂
我个人理解前者是对源码本身的反馈，更聚焦更有目的性；而后者是谈天说地、聊南聊北的空间。

具体看助教 @luffythink  怎么看待吧👀他应该有权限Convert to discussion

**Comment by luffythink** [comment]
挺好的建议👍，报名人数过多的情况下，建一个 Notes_WICL1st 文件夹更清晰，方便大家更好定位笔记文件。
