### ISSUE TITLE
似乎无法自动登记打卡

### ISSUE THREAD

**Issue by ztm0929** [IntensiveCoLearning/Web3-URL#74]
直接在仓库主分支自己的笔记里修改内容后并提交，显示自动化脚本运行成功，但表格里似乎并没有添加记录。

没细看Python代码👀，想确认下，自动化仅限于报名，打卡需要自行记录对吗？

**Comment by brucexu-eth** [comment]
打卡也是自动的，只需要自己提交自己的笔记，脚本应该会自动标记。如果没有，可能是脚本出了问题 @muxin-web3 可以看看

**Comment by muxin-web3** [comment]
> 直接在仓库主分支自己的笔记里修改内容后并提交，显示自动化脚本运行成功，但表格里似乎并没有添加记录。
> 
> 没细看Python代码👀，想确认下，自动化仅限于报名，打卡需要自行记录对吗？

感谢反馈，打卡是 push 代码后自动更新到表格的，已经联系小伙伴在看了。

**Comment by DerickIT** [comment]
感谢反馈，已经fixs bug
